version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - amimart
      - ccamel
    assignees:
      - amimart
      - ccamel
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - amimart
      - ccamel
    assignees:
      - amimart
      - ccamel
